source_event_topic: source_events
source_event_type: source_event
event_store_path: event_store
artifact_topic_prefix: artifact
accession_store_path: accession_store
prefix_mapping:
  Study: GHGAS
  ExperimentMethod: GHGAQ
  Experiment: GHGAX
  ResearchDataFile: GHGAF
  ProcessDataFile: GHGAF
  ExperimentMethodSupportingFile: GHGAF
  AnalysisMethodSupportingFile: GHGAF
  IndividualSupportingFile: GHGAF
  DataAccessPolicy: GHGAP
  DataAccessCommittee: GHGAC
  AnalysisMethod: GHGAZ
  Publication: GHGAU
  Analysis: GHGAR
  Individual: GHGAI
  Sample: GHGAN
  Dataset: GHGAD
suffix_length: 14
metadata_model_path: metadata_model.yaml
submission_store_dir: submission_store
artifact_model_dir: artifact_models
workflow_config:
  normalize_model: {}
  aggregate_stats:
    aggregations:
      - input: Dataset
        output: DatasetStats
        operations:
          - output_path: title
            input_paths:
              - title
            function: StringCopy
          - output_path: dac_email
            input_paths:
              - data_access_policy.data_access_committee.email
            function: StringCopy
          - output_path: types
            input_paths:
              - types
            function: StringListCopy
          - output_path: description
            input_paths:
              - description
            function: StringCopy
          - output_path: samples_summary.count
            input_paths:
              - research_data_files.experiments.sample
              - individual_supporting_files.individual.samples
              - analysis_method_supporting_files.analysis_method.analyses.research_data_files.experiments.sample
              - process_data_files.analysis.research_data_files.experiments.sample
            function: Count
            visit_only_once:
              - Sample
          - output_path: samples_summary.stats.sex
            input_paths:
              - individual_supporting_files.individual.sex
              - analysis_method_supporting_files.analysis_method.analyses.research_data_files.experiments.sample.individual.sex
              - process_data_files.analysis.research_data_files.experiments.sample.individual.sex
              - research_data_files.experiments.sample.individual.sex
            function: StringElementCount
            visit_only_once:
              - Individual
          - output_path: samples_summary.stats.tissues
            input_paths:
              - research_data_files.experiments.sample.biospecimen_tissue_term
              - individual_supporting_files.individual.samples.biospecimen_tissue_term
              - analysis_method_supporting_files.analysis_method.analyses.research_data_files.experiments.sample.biospecimen_tissue_term
              - process_data_files.analysis.research_data_files.experiments.sample.biospecimen_tissue_term
            function: StringElementCount
            visit_only_once:
              - Sample
          - output_path: samples_summary.stats.phenotypic_features
            input_paths:
              - individual_supporting_files.individual.phenotypic_features_terms
              - research_data_files.experiments.sample.individual.phenotypic_features_terms
              - analysis_method_supporting_files.analysis_method.analyses.research_data_files.experiments.sample.individual.phenotypic_features_terms
              - process_data_files.analysis.research_data_files.experiments.sample.individual.phenotypic_features_terms
            function: StringElementCount
            visit_only_once:
              - Individual
          - output_path: studies_summary.count
            input_paths:
              - study
            function: Count
          - output_path: studies_summary.stats.accession
            input_paths:
              - study.accession
            function: StringListCopy
            visit_only_once:
              - Study
          - output_path: studies_summary.stats.title
            input_paths:
              - study.title
            function: StringListCopy
            visit_only_once:
              - Study
          - output_path: experiments_summary.count
            input_paths:
              - research_data_files.experiments
              - individual_supporting_files.individual.samples.experiments
              - analysis_method_supporting_files.analysis_method.analyses.research_data_files.experiments
              - process_data_files.analysis.research_data_files.experiments
              - experiment_method_supporting_files.experiment_method.experiments
            function: Count
            visit_only_once:
              - Experiment
          - output_path: experiments_summary.stats.experiment_methods
            input_paths:
              - experiment_method_supporting_files.experiment_method.instrument_model
              - individual_supporting_files.individual.samples.experiments.experiment_method.instrument_model
              - research_data_files.experiments.experiment_method.instrument_model
              - process_data_files.analysis.research_data_files.experiments.experiment_method.instrument_model
              - analysis_method_supporting_files.analysis_method.analyses.research_data_files.experiments.experiment_method.instrument_model
            function: StringElementCount
            visit_only_once:
              - Experiment
          - output_path: files_summary.count
            input_paths:
              - research_data_files
              - process_data_files
              - experiment_method_supporting_files
              - analysis_method_supporting_files
              - individual_supporting_files
            function: Count
          - output_path: files_summary.stats.format
            input_paths:
              - research_data_files.format
              - process_data_files.format
              - experiment_method_supporting_files.format
              - analysis_method_supporting_files.format
              - individual_supporting_files.format
            function: StringElementCount
  add_accessions:
    accession_slot_name: accession
    accession_slot_description: The accession for an entity.
  embed_restricted:
    embedding_profiles:
      - target_class: EmbeddedDataset
        source_class: Dataset
        description: "Fully embedded dataset."
        embedded_references:
          data_access_policy:
            target_class: EmbeddedDataAccessPolicy
            source_class: DataAccessPolicy
            description: "Fully embedded data access policy."
            embedded_references:
              data_access_committee: DataAccessCommittee
  infer_multiway_references:
    inferred_ref_map:
      AnalysisMethod:
        analyses:
          path: "AnalysisMethod<(analysis_method)Analysis"
          multivalued: True
        analysis_method_supporting_files:
          path: "AnalysisMethod<(analysis_method)AnalysisMethodSupportingFile"
          multivalued: True
      ResearchDataFile:
        analyses:
          path: "ResearchDataFile<(research_data_files)Analysis"
          multivalued: True
      Study:
        datasets:
          path: "Study<(study)Dataset"
          multivalued: True
        publications:
          path: "Study<(study)Publication"
          multivalued: True
      Individual:
        samples:
          path: "Individual<(individual)Sample"
          multivalued: True
        individual_supporting_files:
          path: "Individual<(individual)IndividualSupportingFile"
          multivalued: True
      ExperimentMethod:
        experiment_method_supporting_files:
          path: "ExperimentMethod<(experiment_method)ExperimentMethodSupportingFile"
          multivalued: True
      Sample:
        experiments:
          path: "Sample<(sample)Experiment"
          multivalued: True
      Experiment:
        research_data_files:
          path: "Experiment<(experiments)ResearchDataFile"
          multivalued: True
      Analysis:
        process_data_files:
          path: "Analysis<(analysis)ProcessDataFile"
          multivalued: True
      Dataset:
        process_data_files:
          path: "Dataset<(dataset)ProcessDataFile"
          multivalued: True
        experiment_method_supporting_files:
          path: "Dataset<(dataset)ExperimentMethodSupportingFile"
          multivalued: True
        analysis_method_supporting_files:
          path: "Dataset<(dataset)AnalysisMethodSupportingFile"
          multivalued: True
        individual_supporting_files:
          path: "Dataset<(dataset)IndividualSupportingFile"
          multivalued: True
        research_data_files:
          path: "Dataset<(dataset)ResearchDataFile"
          multivalued: True

        individual_supporting_file_samples:
          path: "Dataset<(dataset)IndividualSupportingFile(individual)>Individual<(individual)Sample"
          multivalued: True
        experiment_method_supporting_file_samples:
          path: "Dataset<(dataset)ExperimentMethodSupportingFile(experiment_method)>ExperimentMethod<(experiment_method)Experiment(sample)>Sample"
          multivalued: True
        processed_data_file_samples:
          path: "Dataset<(dataset)ProcessDataFile(analysis)>Analysis(research_data_files)>ResearchDataFile(experiments)>Experiment(sample)>Sample"
          multivalued: True
        analysis_method_supporting_file_samples:
          path: "Dataset<(dataset)AnalysisMethodSupportingFile(analysis_method)>AnalysisMethod<(analysis_method)Analysis(research_data_files)>ResearchDataFile(experiments)>Experiment(sample)>Sample"
          multivalued: True
        research_data_file_samples:
          path: "Dataset<(dataset)ResearchDataFile(experiments)>Experiment(sample)>Sample"
          multivalued: True

        individual_supporting_file_individuals:
          path: "Dataset<(dataset)IndividualSupportingFile(individual)>Individual"
          multivalued: True
        experiment_method_supporting_file_individuals:
          path: "Dataset(experiment_method_supporting_file_samples)>Sample(individual)>Individual"
          multivalued: True
        processed_data_file_individuals:
          path: "Dataset(processed_data_file_samples)>Sample(individual)>Individual"
          multivalued: True
        analysis_method_supporting_file_individuals:
          path: "Dataset(analysis_method_supporting_file_samples)>Sample(individual)>Individual"
          multivalued: True
        research_data_file_individuals:
          path: "Dataset(research_data_file_samples)>Sample(individual)>Individual"
          multivalued: True
        individual_supporting_file_experiments:
          path: "Dataset<(dataset)IndividualSupportingFile(individual)>Individual<(individual)Sample<(sample)Experiment"
          multivalued: True
        experiment_method_supporting_file_experiments:
          path: "Dataset<(dataset)ExperimentMethodSupportingFile(experiment_method)>ExperimentMethod<(experiment_method)Experiment"
          multivalued: True
        processed_data_file_experiments:
          path: "Dataset<(dataset)ProcessDataFile(analysis)>Analysis(research_data_files)>ResearchDataFile(experiments)>Experiment"
          multivalued: True
        analysis_method_supporting_file_experiments:
          path: "Dataset<(dataset)AnalysisMethodSupportingFile(analysis_method)>AnalysisMethod<(analysis_method)Analysis(research_data_files)>ResearchDataFile(experiments)>Experiment"
          multivalued: True
        research_data_file_experiments:
          path: "Dataset<(dataset)ResearchDataFile(experiments)>Experiment"
          multivalued: True
        individual_supporting_file_experiment_methods:
          path: "Dataset<(dataset)IndividualSupportingFile(individual)>Individual<(individual)Sample<(sample)Experiment(experiment_method)>ExperimentMethod"
          multivalued: True
        experiment_method_supporting_file_experiment_methods:
          path: "Dataset<(dataset)ExperimentMethodSupportingFile(experiment_method)>ExperimentMethod"
          multivalued: True
        processed_data_file_experiment_methods:
          path: "Dataset<(dataset)ProcessDataFile(analysis)>Analysis(research_data_files)>ResearchDataFile(experiments)>Experiment(experiment_method)>ExperimentMethod"
          multivalued: True
        analysis_method_supporting_file_experiment_methods:
          path: "Dataset<(dataset)AnalysisMethodSupportingFile(analysis_method)>AnalysisMethod<(analysis_method)Analysis(research_data_files)>ResearchDataFile(experiments)>Experiment(experiment_method)>ExperimentMethod"
          multivalued: True
        research_data_file_experiment_methods:
          path: "Dataset<(dataset)ResearchDataFile(experiments)>Experiment(experiment_method)>ExperimentMethod"
          multivalued: True
  merge_dataset_file_lists:
    merge_instructions:
      - class_name: Dataset
        source_slots: [individual_supporting_file_experiments, experiment_method_supporting_file_experiments, processed_data_file_experiments, analysis_method_supporting_file_experiments, research_data_file_experiments]
        target_slot: experiments
        target_description: >-
          All experiments associated with the dataset.
      - class_name: Dataset
        source_slots: [research_data_files, process_data_files, individual_supporting_files, experiment_method_supporting_files, analysis_method_supporting_files]
        target_slot: files
        target_description: >-
          All files associated with the dataset.
      - class_name: Dataset
        source_slots: [individual_supporting_file_samples, experiment_method_supporting_file_samples, processed_data_file_samples, analysis_method_supporting_file_samples, research_data_file_samples]
        target_slot: samples
        target_description: >-
          All samples associated with the dataset.
      - class_name: Dataset
        source_slots: [individual_supporting_file_individuals, experiment_method_supporting_file_individuals, processed_data_file_individuals, analysis_method_supporting_file_individuals, research_data_file_individuals]
        target_slot: individuals
        target_description: >-
          All individuals associated with the dataset.
      - class_name: Dataset
        source_slots: [individual_supporting_file_experiment_methods, experiment_method_supporting_file_experiment_methods, processed_data_file_experiment_methods, analysis_method_supporting_file_experiment_methods, research_data_file_experiment_methods]
        target_slot: experiment_methods
        target_description: >-
          All experiment methods associated with the dataset.
  remove_restricted_metadata:
    slots_to_delete:
      Dataset:
      - individual_supporting_file_experiments
      - experiment_method_supporting_file_experiments
      - processed_data_file_experiments
      - analysis_method_supporting_file_experiments
      - research_data_file_experiments
      - individual_supporting_file_samples
      - experiment_method_supporting_file_samples
      - processed_data_file_samples
      - analysis_method_supporting_file_samples
      - research_data_file_samples
      - individual_supporting_file_individuals
      - experiment_method_supporting_file_individuals
      - processed_data_file_individuals
      - analysis_method_supporting_file_individuals
      - research_data_file_individuals
  embed_public:
    embedding_profiles:
      - target_class: EmbeddedDataset
        source_class: Dataset
        description: "Fully embedded dataset."
        embedded_references:
          data_access_policy:
            target_class: EmbeddedDataAccessPolicy
            source_class: DataAccessPolicy
            description: "Fully embedded data access policy."
            embedded_references:
              data_access_committee: DataAccessCommittee
          process_data_files: ProcessDataFile
          study:
            target_class: EmbeddedStudy
            source_class: Study
            description: "Study with Publications embedded"
            embedded_references:
              publications: Publication
          experiments: Experiment
          experiment_methods: ExperimentMethod
          samples: Sample
          individuals: Individual
          experiment_method_supporting_files: ExperimentMethodSupportingFile
          analysis_method_supporting_files: AnalysisMethodSupportingFile
          individual_supporting_files: IndividualSupportingFile
          research_data_files: ResearchDataFile
