[build-system]
requires = ["setuptools>=82"]
build-backend = "setuptools.build_meta"

[project]
name = "pcs"
version = "6.4.0"
description = "Purge Controller Service - a service to commission file deletions"
readme = "README.md"
authors = [
    { name = "German Human Genome Phenome Archive (GHGA)", email = "contact@ghga.de" },
]
requires-python = ">=3.13"
dependencies = [
    "typer >= 0.25",
    "ghga-service-commons[api, auth, crypt, transports] >= 7.0.1",
    "ghga-event-schemas >= 13.0.0",
    "hexkit[akafka, s3, mongodb, opentelemetry] >= 8.3.0",
    "crypt4gh >= 1.7",
    "hvac >= 2",
    "httpx >= 0.28",
    "packaging >= 26",
]
classifiers = [
    "Development Status :: 5 - Production/Stable",
    "Operating System :: POSIX :: Linux",
    "Programming Language :: Python :: 3",
    "Programming Language :: Python :: 3.13",
    "License :: OSI Approved :: Apache Software License",
    "Topic :: Internet :: WWW/HTTP :: HTTP Servers",
    "Topic :: Software Development :: Libraries",
    "Intended Audience :: Developers",
]

[project.urls]
Repository = "https://github.com/ghga-de/file-services-backend/tree/main/services/pcs"

[project.scripts]
pcs = "pcs.__main__:cli"

[project.license]
text = "Apache 2.0"

[tool.setuptools.packages.find]
where = [
    "src",
]

[tool.uv.sources]
ghga-event-schemas = { workspace = true }
ghga-service-commons = { workspace = true }
hexkit = { workspace = true }
