charts:
  access-request:
    name: access-request
    description: Access request service
    appVersion: "7.1.1"
  auth-service:
    name: auth-service
    description: The auth_adapter subpackage contains the authentication service used by the API gateway via the ExtAuth protocol.
    appVersion: "9.0.1"
  data-portal-ui:
    name: data-portal-ui
    description: The Metadata Search Service is a service for providing a unified search interface over a metadata store.
    appVersion: "2.5.3"
  dataset-information:
    name: dataset-information
    description: Dataset Information Service
    appVersion: "6.0.1"
  dead-letter-queue:
    name: dead-letter-queue
    description: DLQ service
    appVersion: "3.1.1"
  download-controller:
    name: download-controller
    description: This service implements the GA4GH DRS, while providing the option to serve files from localstack S3.
    appVersion: "9.1.0"
  upload-controller:
    name: upload-controller
    description: This service manages file uploads.
    appVersion: "12.0.0"
  encryption-key-store:
    name: encryption-key-store
    description: providing crypt4gh file secret extraction, storage and envelope generation
    appVersion: "5.0.1"
  file-ingest:
    name: file-ingest
    description: A lightweight service to propagate file upload metadata to the GHGA file backend services
    appVersion: "11.1.0"
  internal-file-registry:
    name: internal-file-registry
    description: This service acts as a registry for the internal location and representation of files.
    appVersion: "7.1.0"
  mass:
    name: mass
    description: Metadata Artifact Search Service
    appVersion: "6.1.1"
  metldata:
    name: metldata
    description: metldata - A framework for handling metadata based on ETL, CQRS, and event sourcing.
    appVersion: "4.0.9"
  notification:
    name: notification
    description: Notification service
    appVersion: "6.1.1"
  notification-orchestration:
    name: notification-orchestration
    description: Notification orchestration service
    appVersion: "8.2.0"
  purge-controller:
    name: purge-controller
    description: Purge Controller Service
    appVersion: "6.0.0"
  reverse-transpiler:
    name: reverse-transpiler
    description: Reverse Transpiler Service
    appVersion: "2.2.1"
  state-management:
    name: state-management
    description: State Management Service
    appVersion: "4.3.1"
  test-oidc-provider:
    name: test-oidc-provider
    description: A dummy OpenID Connect provider (OP) that can be user for testing purposes.
    appVersion: "1.2.1"
  well-known-value:
    name: well-known-value
    description: Well-known Value Service
    appVersion: "2.1.1"
  work-package:
    name: work-package
    description: Work package service
    appVersion: "10.0.0"
  registry-service:
    name: registry-service
    description: GHGA Registry Service
    appVersion: "1.0.0"
  auth-km-jobs:
    name: auth-km-jobs
    description: This job is to refresh the internal and external auth keys.
    appVersion: "0.2.1"
    version: "2.4.0"
  remotebackup:
    name: remotebackup
    description: remotebackup
    appVersion: "3.1.9"
    version: "3.2.2"
  datahub-monitor:
    name: datahub-monitor
    description: datahub-monitor
    appVersion: "0.1.3"
    version: "0.1.7"
