#!/usr/bin/env python3
"""Generate the per-service Helm charts from workspace metadata.

Chart identity (name, description) and the derivable runtime facts (image
reference, executable, configPrefix, command style) come from the workspace
members enumerated by scripts/image_members.py — the same source the release
workflow uses. Genuine deployment knowledge lives in each member's
chart-values.yaml, co-located with the member.

Conventions baked into the derived values:
- chart name == package name == image name == console script (ADR-0014)
- the monorepo images are shell-less hardened bases -> commandStyle=exec,
  no command prefix (executables resolve via the image PATH)
- image.tag stays empty so the Bitnami image helper falls back to the chart's
  appVersion == the platform version (ADR-0004)
"""

import argparse
import json
import shutil
import sys
from copy import deepcopy
from io import StringIO
from pathlib import Path

from ruamel.yaml import YAML
from ruamel.yaml.scalarstring import DoubleQuotedScalarString

DEPLOY_ROOT = Path(__file__).resolve().parents[1]
REPO_ROOT = DEPLOY_ROOT.parent
OUTPUT_DIR = DEPLOY_ROOT / "charts"
LIBRARY_VALUES = DEPLOY_ROOT / "charts" / "ghga-common" / "values.yaml"
LIBRARY_SCHEMA = DEPLOY_ROOT / "charts" / "ghga-common" / "values.schema.json"
CHART_TEMPLATE = DEPLOY_ROOT / "src" / "template"
DEMO_CHART = OUTPUT_DIR / "ghga-demo"
# name of the single image carrying every Python member (docker/Dockerfile VARIANT=mono)
MONO_IMAGE = "platform"

sys.path.insert(0, str(REPO_ROOT / "scripts"))
from image_members import image_members

YAML_PARSER = YAML()
YAML_PARSER.preserve_quotes = True
# never fold long plain scalars: ruamel breaks them mid-line and leaves a trailing
# space before the fold, which the trailing-whitespace hook would strip and the next
# generator run would put straight back
YAML_PARSER.width = 4096

VALUES_HEADER = """\
# Generated by create_charts.py — do not edit. Composition (later wins):
#   1. ghga-common library defaults (exports.defaults, flattened here: helm's
#      import-values is not processed for aliased chart instances, so the
#      defaults are baked in at generation time instead)
#   2. facts derived from workspace metadata
#   3. deployment values from {source}
"""


def deep_merge(base, override):
    """Helm-style value coalescing: maps merge recursively, everything else replaces."""
    if isinstance(base, dict) and isinstance(override, dict):
        merged = dict(base)
        for key, value in override.items():
            merged[key] = deep_merge(merged[key], value) if key in merged else value
        return merged
    return override


def derived_values(member: dict, registry: str) -> dict:
    """Values derived from workspace metadata for one member chart."""
    registry_host, _, repo_prefix = registry.partition("/")
    values: dict = {
        "image": {
            "registry": registry_host,
            "repository": f"{repo_prefix}/{member['package']}"
            if repo_prefix
            else member["package"],
        },
        "configPrefix": member["package"].replace("-", "_"),
        "commandStyle": "exec",
        "commandPrefix": "",
    }
    if member["kind"] == "python":
        # console script == package name (enforced at image build); frontend images
        # run via their ENTRYPOINT instead, so no executable is set for them
        values["executable"] = member["package"]
    return values


def stamp_chart(
    name: str,
    description: str,
    version: str,
    app_version: str,
    values_text: str,
) -> Path:
    """Stamp one chart from the template with the given identity and values."""
    chart_dir = OUTPUT_DIR / name
    if chart_dir.exists():
        shutil.rmtree(chart_dir)
    # never propagate resolved-dependency artifacts from the template: a vendored
    # library .tgz would silently shadow the file:// dependency at install time
    shutil.copytree(
        CHART_TEMPLATE, chart_dir, ignore=shutil.ignore_patterns("Chart.lock", "charts")
    )

    with (CHART_TEMPLATE / "Chart.yaml").open("r", encoding="utf-8") as chart_yaml_file:
        chart_yaml = YAML_PARSER.load(chart_yaml_file)
    chart_yaml = deepcopy(chart_yaml)
    chart_yaml["name"] = name
    chart_yaml["description"] = description
    chart_yaml["version"] = DoubleQuotedScalarString(version)
    chart_yaml["appVersion"] = DoubleQuotedScalarString(app_version)
    with (chart_dir / "Chart.yaml").open("w", encoding="utf-8") as chart_yaml_file:
        YAML_PARSER.dump(chart_yaml, chart_yaml_file)

    (chart_dir / "values.yaml").write_text(values_text.rstrip("\n") + "\n")
    return chart_dir


def _plain(value):
    """Rebuild a ruamel round-trip structure as plain dict/list, dropping comments.

    Comments carry their source indentation as a raw string; re-nesting a
    CommentedMap a level shallower (exports.defaults -> a member's values.yaml
    root) doesn't recalculate that indentation, so a comment above a key would end
    up misindented relative to it. deep_merge() and chart_values_schema() below
    both need comment-free plain data to work with; ghga-common/values.schema.json
    (not values.yaml's own comments) is the source of the descriptions that reach
    a derived chart's own values.schema.json.
    """
    if isinstance(value, dict):
        return {key: _plain(item) for key, item in value.items()}
    if isinstance(value, list):
        return [_plain(item) for item in value]
    return value


def _docs_from_schema(schema: dict, prefix: str = "") -> dict[str, str]:
    """Flatten a JSON Schema's `description`s into {dotted.path: text}.

    ghga-common/values.schema.json (hand-authored, alongside values.yaml) is the
    single source of truth for what every derived chart's own values.schema.json
    documents; this is the read side of that, used by chart_values_schema() below.
    """
    docs: dict[str, str] = {}
    description = schema.get("description")
    if description and prefix:
        docs[prefix] = description
    for key, child in schema.get("properties", {}).items():
        docs.update(_docs_from_schema(child, f"{prefix}.{key}" if prefix else key))
    return docs


def library_docs() -> dict[str, str]:
    """Descriptions from ghga-common/values.schema.json, keyed by dotted path."""
    with LIBRARY_SCHEMA.open("r", encoding="utf-8") as schema_file:
        return _docs_from_schema(json.load(schema_file))


def _json_type(value) -> str | None:
    """Map a Python value to its JSON Schema type keyword; None for null."""
    if isinstance(value, bool):
        return "boolean"
    if isinstance(value, (int, float)):
        return "number"
    if isinstance(value, str):
        return "string"
    if isinstance(value, list):
        return "array"
    if isinstance(value, dict):
        return "object"
    return None


def _schema_for(value, docs: dict[str, str], prefix: str = "") -> dict:
    """Build one loose JSON Schema node: known keys typed+described, nothing forbidden.

    Deliberately shallow beyond what the data itself gives: this documents and
    type-hints values, it doesn't attempt to fully model Kubernetes' own API shapes
    (resources, affinity, tolerations, ...) or a service's free-form `config` block.
    additionalProperties stays true on every object and arrays get no `items`
    constraint, so a real per-member override can never fail `helm lint`/`helm
    template` schema validation just because this generator didn't know about it.
    """
    schema: dict = {}
    node_type = _json_type(value)
    if node_type:
        schema["type"] = node_type
    description = docs.get(prefix)
    if description:
        schema["description"] = description
    if node_type == "object":
        schema["additionalProperties"] = True
        if value:
            schema["properties"] = {
                key: _schema_for(item, docs, f"{prefix}.{key}" if prefix else key)
                for key, item in value.items()
            }
    return schema


def chart_values_schema(values: dict, docs: dict[str, str]) -> dict:
    """A loose values.schema.json for one chart: documents and type-hints, never forbids."""
    return {
        "$schema": "http://json-schema.org/draft-07/schema#",
        **_schema_for(values, docs),
    }


def library_defaults() -> dict:
    """The library chart's exported defaults (exports.defaults)."""
    with LIBRARY_VALUES.open("r", encoding="utf-8") as library_file:
        loaded = YAML_PARSER.load(library_file)["exports"]["defaults"]
    return _plain(loaded)


def current_member_version() -> str:
    """The platform version already stamped on the generated member charts.

    The version is an input to this generator, not a property of it (ADR-0004):
    release-charts.yaml publishes whatever is committed, so regenerating without an
    explicit version must preserve it.
    """
    generated = [
        values_file.parent
        for values_file in sorted(OUTPUT_DIR.glob("*/values.yaml"))
        if values_file.read_text().startswith("# Generated by create_charts.py")
    ]
    if not generated:
        sys.exit(
            f"no generated charts under {OUTPUT_DIR}/ - has the generator changed?"
        )

    by_version: dict[str, list[str]] = {}
    for chart_dir in generated:
        chart_yaml = chart_dir / "Chart.yaml"
        if not chart_yaml.is_file():
            sys.exit(f"{chart_yaml} is missing")
        with chart_yaml.open("r", encoding="utf-8") as chart_yaml_file:
            loaded = YAML_PARSER.load(chart_yaml_file)
        if not loaded or "version" not in loaded:
            sys.exit(f"no `version:` key in {chart_yaml}")
        by_version.setdefault(str(loaded["version"]), []).append(chart_dir.name)

    if len(by_version) > 1:
        detail = "; ".join(
            f"{version} ({', '.join(charts)})"
            for version, charts in sorted(by_version.items())
        )
        sys.exit(
            f"the member charts disagree on their version: {detail}\n"
            "The platform lane is lockstep - one version for everything deployable -\n"
            "so `just charts <version>` stamps them all. Re-run it."
        )
    return next(iter(by_version))


def compose_member_values(
    member: dict, registry: str, defaults: dict
) -> tuple[dict, str]:
    """Merge one member chart's values: defaults <- derived <- chart-values."""
    source = f"{member['path']}/chart-values.yaml"
    values = deep_merge(defaults, derived_values(member, registry))

    values_file = REPO_ROOT / member["path"] / "chart-values.yaml"
    if values_file.is_file():
        member_values = YAML_PARSER.load(values_file.read_text()) or {}
        values = deep_merge(values, _plain(member_values))
    else:
        source = f"{source} (absent; library defaults only)"
        print(
            f"note: {member['path']} has no chart-values.yaml; using library defaults"
        )
    return values, source


def member_values_text(values: dict, source: str) -> str:
    """Render one member chart's merged values as values.yaml text."""
    buffer = StringIO()
    buffer.write(VALUES_HEADER.format(source=source))
    YAML_PARSER.dump(values, buffer)
    return buffer.getvalue()


MONO_HEADER = """\
# Generated by create_charts.py — do not edit.
#
# Mono-image overlay for the demo umbrella: points every Python member's deployment at
# the single image built by `just demo-images-mono` instead of its own. Layer it AFTER
# values-local.yaml (which supplies tag: local):
#
#   just up mono          # or: helm upgrade ... -f values-local.yaml -f values-mono.yaml
#
# One entry per umbrella dependency, keyed by ALIAS where the chart is instantiated more
# than once — an aliased instance takes its values under the alias, not the chart name.
# Members shipping their own Dockerfile (the frontend) keep their own image and are
# deliberately absent here.
#
# Plus any image the UMBRELLA's own templates run (the secret-gen job and friends): those
# are not dependencies, so the alias pass cannot see them, and missing one leaves a job in
# ImagePullBackOff with helm blocked on its pre-install hook — a silent 15-minute hang.
"""


def _member_image_paths(node, registry: str, packages: set, path: tuple = ()):
    """Yield value paths in the umbrella values that point at a per-member image.

    Only maps are traversed: a list index cannot be addressed from a values overlay.
    """
    if isinstance(node, dict):
        for key, value in node.items():
            if (
                key == "repository"
                and isinstance(value, str)
                and value.startswith(f"{registry}/")
                and value.rsplit("/", 1)[-1] in packages
            ):
                yield (*path, key)
            else:
                yield from _member_image_paths(value, registry, packages, (*path, key))


def _nest(path: tuple, value) -> dict:
    """Build the nested mapping that sets `value` at `path`."""
    for key in reversed(path):
        value = {key: value}
    return value


def mono_overlay_text(registry: str) -> str:
    """Overlay redirecting every Python member instance to the mono image."""
    _, _, repo_prefix = registry.partition("/")
    repository = f"{repo_prefix}/{MONO_IMAGE}" if repo_prefix else MONO_IMAGE
    python_packages = {m["package"] for m in image_members() if m["kind"] == "python"}

    with (DEMO_CHART / "Chart.yaml").open("r", encoding="utf-8") as demo_chart_file:
        dependencies = YAML_PARSER.load(demo_chart_file)["dependencies"]

    overlay = {
        dep.get("alias", dep["name"]): {"image": {"repository": repository}}
        for dep in dependencies
        if dep["name"] in python_packages
    }
    if not overlay:
        raise RuntimeError(
            "no Python member instances found in the ghga-demo dependencies — "
            "the mono overlay would silently do nothing"
        )

    # umbrella-level images (full reference, registry included — these do not go through
    # the library chart's registry/repository split)
    with (DEMO_CHART / "values.yaml").open("r", encoding="utf-8") as demo_values_file:
        demo_values = YAML_PARSER.load(demo_values_file)
    for path in _member_image_paths(demo_values, registry, python_packages):
        overlay = deep_merge(overlay, _nest(path, f"{registry}/{MONO_IMAGE}"))

    buffer = StringIO()
    buffer.write(MONO_HEADER)
    YAML_PARSER.dump(overlay, buffer)
    return buffer.getvalue()


def chart_readme_text(
    name: str, description: str, path: str, chart_registry: str
) -> str:
    """Chart root README.md — `helm package` bundles it into the .tgz (Helm convention;
    also what Artifact Hub reads as the chart's Overview, were this repo ever listed
    there), and release.yaml's Docker Hub overview PATCH reuses the same file.

    No `--version` pin in the install snippet: this file is regenerated at every
    release, so a pinned version here would need updating on every single one - omit
    it and Helm just installs the latest published version, which is what's true at
    the time anyone actually reads this.
    """
    return f"""\
# {name}

{description}

## Installing

```
helm install {name} oci://{chart_registry}/{name}-chart
```

## Source

Part of the [GHGA monorepo](https://github.com/ghga-de/ghga/tree/main/{path}). See
[values.yaml](values.yaml) for the full set of configurable values.
"""


def main() -> None:
    """Regenerate all charts from workspace members."""
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument(
        "--version",
        help=(
            "platform version stamped as chart version and appVersion (ADR-0004);"
            " defaults to the version already on the generated member charts"
        ),
    )
    parser.add_argument(
        "--registry",
        default="docker.io/ghga",
        help="image registry root; the package name is appended per member",
    )
    parser.add_argument(
        "--chart-registry",
        default="registry-1.docker.io/ghga",
        help=(
            "OCI registry root charts are published under (release.yaml's"
            " CHART_REGISTRY); used only for each chart README's install snippet"
        ),
    )
    args = parser.parse_args()

    # resolved before the first stamp_chart(), which rmtree()s the chart directories
    version = args.version or current_member_version()

    defaults = library_defaults()
    docs = library_docs()
    for member in image_members():
        description = member["description"] or member["package"]
        values, source = compose_member_values(member, args.registry, defaults)
        chart_dir = stamp_chart(
            name=member["package"],
            description=description,
            version=version,
            app_version=version,
            values_text=member_values_text(values, source),
        )
        schema = chart_values_schema(values, docs)
        (chart_dir / "values.schema.json").write_text(
            json.dumps(schema, indent=2) + "\n"
        )
        (chart_dir / "README.md").write_text(
            chart_readme_text(
                name=member["package"],
                description=description,
                path=member["path"],
                chart_registry=args.chart_registry,
            )
        )
        print(f"Created chart for {member['package']} at {chart_dir}")

    mono_values = DEMO_CHART / "values-mono.yaml"
    mono_values.write_text(mono_overlay_text(args.registry).rstrip("\n") + "\n")
    print(f"Created mono-image overlay at {mono_values}")


if __name__ == "__main__":
    main()
