# Copyright 2021 - 2022 Universität Tübingen, DKFZ and EMBL
# for the German Human Genome-Phenome Archive (GHGA)

[metadata]
# Please adapt to package name:
name = auth_km_jobs
version = attr: auth_km_jobs.__version__
description = GHGA Auth Key Managagement Jobs
url = https://github.com/ghga-de/auth_km_jobs
long_description = file: README.md
long_description_content_type = text/markdown; charset=UTF-8
author = German Human Genome Phenome Archive (GHGA)
author_email = contact@ghga.de
license = None
classifiers =
    Operating System :: POSIX :: Linux
    Programming Language :: Python :: 3.9
    Programming Language :: Python :: 3.10
    License :: OSI Approved :: Apache Software License

[options]
zip_safe = False
include_package_data = True
packages = find:
install_requires = 
    typer==0.7.0
    pydantic==1.10.6
    httpx==0.23.3
    jwcrypto==1.5.0
    pynacl==1.5.0
    hvac==1.1.0

python_requires = >= 3.9

[options.entry_points]
console_scripts =
    run = auth_km_jobs.__main__:app

[options.packages.find]
exclude = tests
