[build-system]
requires = [
    "setuptools>=82",
]
build-backend = "setuptools.build_meta"

[project]
readme = "README.md"
authors = [
    { name = "German Human Genome Phenome Archive (GHGA)", email = "contact@ghga.de" },
]
requires-python = ">=3.13"
classifiers = [
    "Development Status :: 5 - Production/Stable",
    "Operating System :: POSIX :: Linux",
    "Programming Language :: Python :: 3",
    "Programming Language :: Python :: 3.13",
    "License :: OSI Approved :: Apache Software License",
    "Topic :: Internet :: WWW/HTTP :: HTTP Servers",
    "Topic :: Software Development :: Libraries",
    "Intended Audience :: Developers",
]
name = "rs"
version = "5.0.0"
description = "GHGA Registry Service - a service for ingesting and archiving metadata from data submitters."
dependencies = [
    "typer >= 0.26",
    "ghga-service-commons[api,auth] >= 7.0",
    "ghga-event-schemas ~= 13.0",
    "hexkit[akafka,mongodb,opentelemetry] >= 8.4",
]

[project.license]
text = "Apache 2.0"

[project.urls]
Repository = "https://github.com/ghga-de/ghga-registry-service"

[project.scripts]
rs = "rs.__main__:cli"

[tool.setuptools.packages.find]
where = [
    "src",
]

[tool.pytest.ini_options]
minversion = "9.0"
asyncio_mode = "strict"
asyncio_default_fixture_loop_scope = "function"

[tool.coverage.paths]
source = [
    "src",
    "/workspace/src",
    "**/lib/python*/site-packages",
]

[tool.uv.sources]
ghga-event-schemas = { workspace = true }
ghga-service-commons = { workspace = true }
hexkit = { workspace = true }
