[build-system]
requires = [
    "setuptools>=82",
]
build-backend = "setuptools.build_meta"

[project]
readme = "README.md"
authors = [
    { name = "German Human Genome Phenome Archive (GHGA)", email = "contact@ghga.de" },
]
requires-python = ">=3.13"
classifiers = [
    "Development Status :: 5 - Production/Stable",
    "Operating System :: POSIX :: Linux",
    "Programming Language :: Python :: 3",
    "Programming Language :: Python :: 3.13",
    "License :: OSI Approved :: Apache Software License",
    "Topic :: Internet :: WWW/HTTP :: HTTP Servers",
    "Topic :: Software Development :: Libraries",
    "Intended Audience :: Developers",
]
name = "dlqs"
version = "4.1.0"
description = "DLQ Service - a service to manage the dead letter queue for Kafka events"
dependencies = [
    "typer >= 0.19",
    "ghga-service-commons[api] >= 7.0",
    "hexkit[akafka,mongodb] >= 8.0",
]

[project.license]
text = "Apache 2.0"

[project.urls]
Repository = "https://github.com/ghga-de/dlq-service"

[project.scripts]
dlqs = "dlqs.__main__:cli"

[tool.setuptools.packages.find]
where = [
    "src",
]

[tool.pytest.ini_options]
minversion = "9.0"
asyncio_mode = "strict"
asyncio_default_fixture_loop_scope = "function"

[tool.coverage.paths]
source = [
    "src",
    "/workspace/src",
    "**/lib/python*/site-packages",
]

[tool.uv.sources]
ghga-service-commons = { workspace = true }
hexkit = { workspace = true }
