"""Turn generated metldata artifact models into a helm values overlay.

Run from testbed/example_data/metadata (see `just testbed-artifacts`); reads
artifact_models/artifact_infos.json, blanks the bulky json_schema bodies the
same way the legacy create_metldata_yaml.sh did, and writes the overlay
consumed by `just testbed-up`.
"""

import json
import pathlib

import yaml


def blank_schemas(node):
    """Replace every json_schema value with an empty object, recursively."""
    if isinstance(node, dict):
        return {
            k: ({} if k == "json_schema" else blank_schemas(v)) for k, v in node.items()
        }
    if isinstance(node, list):
        return [blank_schemas(v) for v in node]
    return node


def main() -> None:
    """Write deploy/charts/ghga-demo/values-artifacts.yaml."""
    infos = json.loads(pathlib.Path("artifact_models/artifact_infos.json").read_text())
    values = {"metldata": {"config": {"artifact_infos": blank_schemas(infos)}}}
    out = pathlib.Path("../../../deploy/charts/ghga-demo/values-artifacts.yaml")
    out.write_text(
        "# GENERATED by `just testbed-artifacts` — do not edit\n"
        + yaml.safe_dump(values)
    )
    print(f"wrote {out.resolve()}")


if __name__ == "__main__":
    main()
