#!/usr/bin/env python3
"""Generate the configuration docs of each member from its Config class.

A member takes part when it has a `config_schema.json`.
For each one the script loads `<package>.config.Config` from the member's
`dev_config.yaml` and writes:

- `config_schema.json`, the JSON Schema of the settings;
- `example_config.yaml`, the loaded settings, with secrets masked;
- the parameter list in the README, between the `config-docs` markers.

With `--check` it writes nothing and fails when a file is out of date.
It ports the retired template's scripts/update_config_docs.py and the config part of
its scripts/update_readme.py, so the output matches what the single-service
repositories generated, apart from what rumdl reflows.

Usage:
    uv run python scripts/config_docs.py [--check] [member ...]
"""

from __future__ import annotations

import argparse
import difflib
import importlib
import json
import os
import pathlib
import re
import subprocess
import sys

import jsonschema2md
import yaml

ROOT = pathlib.Path(__file__).resolve().parents[1]
MEMBER_GLOBS = ("libs/*", "services/*", "tools/*")
SCHEMA_FILE = "config_schema.json"
EXAMPLE_FILE = "example_config.yaml"
DEV_CONFIG_FILE = "dev_config.yaml"
README_FILE = "README.md"
BEGIN_MARKER = (
    "<!-- config-docs: begin (generated by `just config-docs`, do not edit) -->"
)
END_MARKER = "<!-- config-docs: end -->"

# A bare URL, not already inside <...> or a Markdown link target; trailing
# punctuation belongs to the sentence, not to the URL.
BARE_URL = re.compile(r"(?<![<(])\bhttps?://\w[^\s<>)]*?(?=[.,;:]?(?:\s|$))")
INLINE_CODE = re.compile(r"(`+).*?\1")


def members(names: list[str]) -> list[pathlib.Path]:
    """The member directories that carry a config schema, all or the named ones."""
    found = sorted(
        path.parent
        for pattern in MEMBER_GLOBS
        for path in ROOT.glob(f"{pattern}/{SCHEMA_FILE}")
    )
    if not names:
        return found
    wanted = {(ROOT / name).resolve() for name in names}
    unknown = wanted - set(found)
    if unknown:
        sys.exit(f"error: no {SCHEMA_FILE} in {', '.join(sorted(map(str, unknown)))}")
    return [member for member in found if member in wanted]


def package_name(member: pathlib.Path) -> str:
    """The member's single import package under src/."""
    packages = [
        path.name
        for path in (member / "src").iterdir()
        if (path / "__init__.py").is_file()
    ]
    if len(packages) != 1:
        sys.exit(f"error: expected one package under {member}/src, found {packages}")
    return packages[0]


def load_config(member: pathlib.Path):
    """Instantiate the member's Config from its dev config.

    The schema comes from the instance rather than from `Config`, because hexkit's
    `config_from_yaml` turns the class into a constructor function.
    """
    package = package_name(member)
    source = member / DEV_CONFIG_FILE
    if not source.is_file():
        sys.exit(f"error: {member} has a {SCHEMA_FILE} but no {DEV_CONFIG_FILE}")
    # Some config modules build a module-level CONFIG on import, which reads the YAML
    # named by this variable, as the member's conftest.py sets it for the tests.
    os.environ.setdefault(f"{package.upper()}_CONFIG_YAML", str(source))
    module = importlib.import_module(f"{package}.config")
    return module.Config(config_yaml=source)


def render_schema(config) -> str:
    """The JSON Schema of the settings, as the template wrote it."""
    return json.dumps(type(config).model_json_schema(), indent=2) + "\n"


def render_example(config) -> str:
    """The example config YAML, as the template wrote it."""
    settings = config.model_dump(mode="json", by_alias=True)
    return yaml.dump(settings, indent=2, sort_keys=True)


def render_parameters(schema: str) -> str:
    """The Markdown parameter list, with the schema's $defs under a subheading."""
    parser = jsonschema2md.Parser(examples_as_yaml=False, show_examples="all")
    lines = parser.parse_schema(flatten_descriptions(json.loads(schema)))
    lines = lines[lines.index("## Properties\n\n") + 1 :]
    text = "".join(lines).strip()
    text = text.replace("\n## Definitions\n", "\n#### Definitions\n")
    return wrap_bare_urls(text)


def flatten_descriptions(node):
    """The schema with each description on one line.

    jsonschema2md copies a docstring's line breaks into the list item, where they end
    it, and turns a blank line into <br>; rumdl then puts each sentence on its own line.
    """
    if isinstance(node, dict):
        return {
            key: " ".join(value.split())
            if key == "description" and isinstance(value, str)
            else flatten_descriptions(value)
            for key, value in node.items()
        }
    if isinstance(node, list):
        return [flatten_descriptions(item) for item in node]
    return node


def wrap_bare_urls(text: str) -> str:
    """Wrap bare URLs in <...> outside code blocks, as rumdl's MD034 asks."""
    lines, in_code = [], False
    for line in text.splitlines(keepends=True):
        if line.lstrip().startswith("```"):
            in_code = not in_code
        elif not in_code:
            line = wrap_outside_code_spans(line)
        lines.append(line)
    return "".join(lines)


def wrap_outside_code_spans(line: str) -> str:
    """Wrap the bare URLs of one line, leaving `code spans` alone."""
    parts, start = [], 0
    for span in INLINE_CODE.finditer(line):
        parts.append(BARE_URL.sub(r"<\g<0>>", line[start : span.start()]))
        parts.append(span.group(0))
        start = span.end()
    parts.append(BARE_URL.sub(r"<\g<0>>", line[start:]))
    return "".join(parts)


def format_markdown(text: str, path: pathlib.Path) -> str:
    """Apply rumdl's fixes, one sentence per line among them, as the pre-commit hook does."""
    result = subprocess.run(
        [
            "rumdl",
            "fmt",
            "-",
            "--stdin-filename",
            str(path.relative_to(ROOT)),
            "--silent",
        ],
        input=text,
        capture_output=True,
        text=True,
        cwd=ROOT,
        check=False,
    )
    # rumdl exits 1 when unfixable issues remain; those the hook reports anyway
    if result.returncode not in (0, 1) or not result.stdout:
        sys.exit(f"error: rumdl failed on {path}:\n{result.stderr}")
    return result.stdout


def render_readme(readme: pathlib.Path, parameters: str) -> str:
    """The README with the parameter list between the markers replaced."""
    text = readme.read_text()
    begin, end = text.find(BEGIN_MARKER), text.find(END_MARKER)
    if begin < 0 or end < begin:
        sys.exit(f"error: {readme} lacks the config-docs markers")
    text = text[: begin + len(BEGIN_MARKER)] + "\n\n" + parameters + "\n\n" + text[end:]
    return format_markdown(text, readme)


def expected_files(member: pathlib.Path) -> dict[pathlib.Path, str]:
    """Each generated file of the member and the content it should have."""
    config = load_config(member)
    schema = render_schema(config)
    files = {
        member / SCHEMA_FILE: schema,
        member / EXAMPLE_FILE: render_example(config),
    }
    readme = member / README_FILE
    files[readme] = render_readme(readme, render_parameters(schema))
    return files


def main() -> int:
    """Update or check the configuration docs."""
    parser = argparse.ArgumentParser(description=__doc__.splitlines()[0])
    parser.add_argument("--check", action="store_true", help="fail on stale files")
    parser.add_argument("members", nargs="*", help="member paths, default all")
    args = parser.parse_args()

    stale = []
    for member in members(args.members):
        for path, content in expected_files(member).items():
            current = path.read_text() if path.is_file() else ""
            if current == content:
                continue
            stale.append(path.relative_to(ROOT))
            if args.check:
                sys.stdout.writelines(
                    difflib.unified_diff(
                        current.splitlines(keepends=True),
                        content.splitlines(keepends=True),
                        fromfile=f"{path.relative_to(ROOT)} (committed)",
                        tofile=f"{path.relative_to(ROOT)} (generated)",
                    )
                )
            else:
                path.write_text(content)

    if not stale:
        return 0
    listing = "\n".join(f"  {path}" for path in stale)
    if args.check:
        print(f"\nOut of date; run `just config-docs`:\n{listing}", file=sys.stderr)
        return 1
    print(f"Updated:\n{listing}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
