apiVersion: v1
kind: Service
metadata:
  name: {{ include "aai.fullname" . }}
  labels: {{- include "aai.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - name: http
      port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
  selector: {{- include "aai.selectorLabels" . | nindent 4 }}
