// @ts-check
import markdown from '@eslint/markdown';
import angularEslint from 'angular-eslint';
import eslintConfigPrettier from 'eslint-config-prettier/flat';
import boundaries from 'eslint-plugin-boundaries';
import jsdoc from 'eslint-plugin-jsdoc';
import tseslint from 'typescript-eslint';
import requireFileHeader from './eslint-local-rules/require-file-header.js';
import umamiEventMaxLength from './eslint-local-rules/umami-event-max-length.js';

// Define the configuration
export default tseslint.config(
  {
    ignores: [
      '.angular/**',
      'dist/**',
      'documentation/**',
      'out-tsc/**',
      'playwright-report/**',
      'test-results/**',
      'tmp/**',
      // Generated by MSW; not our code to lint
      'src/mocks/mockServiceWorker.js',
      // Build tooling configs: outside the app's tsconfig and lint scope
      'playwright.config.ts',
      'vitest.config.ts',
      'vitest.ui.config.ts',
    ],
  },
  // Configuration for TypeScript files
  {
    files: ['**/*.ts'],
    extends: [tseslint.configs.recommended, angularEslint.configs.tsRecommended],
    languageOptions: {
      parserOptions: {
        ecmaVersion: 2020,
        sourceType: 'module',
        project: './tsconfig.spec.json',
      },
    },
    processor: angularEslint.processInlineTemplates,
    plugins: {
      jsdoc,
      boundaries,
      local: {
        rules: {
          'require-file-header': requireFileHeader,
        },
      },
    },
    rules: {
      ...jsdoc.configs['recommended-typescript'].rules,
      // Allow deliberately unused symbols when prefixed with an underscore
      // (e.g. interface-mandated parameters that the implementation ignores)
      '@typescript-eslint/no-unused-vars': [
        'error',
        {
          argsIgnorePattern: '^_',
          varsIgnorePattern: '^_',
          caughtErrorsIgnorePattern: '^_',
        },
      ],
      '@angular-eslint/directive-selector': [
        'error',
        { type: 'attribute', prefix: 'app', style: 'camelCase' },
      ],
      '@angular-eslint/component-selector': [
        'error',
        { type: 'element', prefix: 'app', style: 'kebab-case' },
      ],
      '@angular-eslint/prefer-on-push-component-change-detection': 'error',
      'local/require-file-header': 'error',
      'jsdoc/require-jsdoc': [
        'warn',
        {
          exemptEmptyConstructors: true,
          require: {
            FunctionDeclaration: true,
            MethodDefinition: true,
            ClassDeclaration: true,
            ArrowFunctionExpression: false,
            FunctionExpression: true,
          },
        },
      ],
      'jsdoc/require-description': [
        'warn',
        {
          contexts: ['FunctionDeclaration', 'MethodDefinition', 'ClassDeclaration'],
        },
      ],
      ...boundaries.configs.strict.rules,
      'boundaries/dependencies': [
        2,
        {
          // disallow importing any element by default
          default: 'disallow',
          // the default error message
          message:
            '{{from.captured.context}}/{{from.type}} is not allowed to import from {{to.captured.context}}/{{to.type}}',
          // all policies will be checked in order and matching policies alter the result
          policies: [
            // generally allow only importing from same context
            {
              from: { element: { type: '*' } },
              allow: {
                to: {
                  element: {
                    type: '*',
                    captured: { context: '{{from.captured.context}}' },
                  },
                },
              },
            },
            {
              from: { element: { type: '*' } },
              disallow: {
                to: {
                  element: {
                    type: '*',
                    captured: { context: '!{{from.captured.context}}' },
                  },
                },
              },
              message:
                '{{from.captured.context}} is not allowed to import from {{to.captured.context}}',
            },
            {
              from: { element: { type: '*' } },
              allow: {
                to: { element: { type: '*', captured: { context: 'shared' } } },
              },
            },
            // overarching portal context may import other feature components
            {
              from: { element: { type: 'features', captured: { context: 'portal' } } },
              allow: {
                to: {
                  element: {
                    type: 'features',
                    captured: {
                      context: ['metadata', 'ivas', 'access-requests', 'auth'],
                    },
                  },
                },
              },
            },
            // access requests context may import from verification addresses context
            {
              from: {
                element: { type: 'features', captured: { context: 'access-requests' } },
              },
              allow: {
                to: [
                  { element: { type: 'service', captured: { context: 'ivas' } } },
                  { element: { type: 'model', captured: { context: 'ivas' } } },
                  { element: { type: 'pipe', captured: { context: 'ivas' } } },
                ],
              },
            },
            {
              from: {
                element: { type: 'model', captured: { context: 'access-requests' } },
              },
              allow: {
                to: [{ element: { type: 'model', captured: { context: 'ivas' } } }],
              },
            },
            // upload context may import from verification addresses and metadata context
            {
              from: { element: { type: 'features', captured: { context: 'upload' } } },
              allow: {
                to: [
                  { element: { type: 'service', captured: { context: 'ivas' } } },
                  { element: { type: 'model', captured: { context: 'ivas' } } },
                  { element: { type: 'pipe', captured: { context: 'ivas' } } },
                  { element: { type: 'service', captured: { context: 'metadata' } } },
                  { element: { type: 'model', captured: { context: 'metadata' } } },
                ],
              },
            },
            // work-package context may import from some other contexts
            {
              from: {
                element: { type: 'features', captured: { context: 'work-packages' } },
              },
              allow: {
                to: [
                  { element: { type: 'service', captured: { context: 'ivas' } } },
                  { element: { type: 'model', captured: { context: 'ivas' } } },
                  { element: { type: 'pipe', captured: { context: 'ivas' } } },
                  {
                    element: {
                      type: 'model',
                      captured: { context: 'access-requests' },
                    },
                  },
                  { element: { type: 'model', captured: { context: 'upload' } } },
                ],
              },
            },
            // auth context may import from verification addresses and access request context
            {
              from: { element: { type: 'features', captured: { context: 'auth' } } },
              allow: {
                to: [
                  { element: { type: 'service', captured: { context: 'ivas' } } },
                  { element: { type: 'model', captured: { context: 'ivas' } } },
                  { element: { type: 'pipe', captured: { context: 'ivas' } } },
                  { element: { type: 'features', captured: { context: 'ivas' } } },
                  {
                    element: {
                      type: 'service',
                      captured: { context: 'access-requests' },
                    },
                  },
                  {
                    element: {
                      type: 'model',
                      captured: { context: 'access-requests' },
                    },
                  },
                  {
                    element: { type: 'pipe', captured: { context: 'access-requests' } },
                  },
                  {
                    element: {
                      type: 'features',
                      captured: { context: 'access-requests' },
                    },
                  },
                ],
              },
            },
            // main may only import config, main app modules and mock setup (dev mode)
            {
              from: { file: { categories: 'main' } },
              disallow: { to: { element: { type: '*' } } },
              message:
                'Main modules may only import config, main app modules and mock setup',
            },
            {
              from: { file: { categories: 'main' } },
              allow: {
                to: [
                  { file: { categories: ['config', 'main-app'] } },
                  { element: { type: 'mock' } },
                ],
              },
            },
            // main app may only import features and shared modules
            {
              from: { file: { categories: 'main-app' } },
              disallow: { to: { element: { type: '*' } } },
              message:
                'Main app component may only import portal features and shared code',
            },
            {
              from: { file: { categories: 'main-app' } },
              allow: {
                to: [
                  { element: { type: 'features', captured: { context: 'portal' } } },
                  { element: { type: '*', captured: { context: 'shared' } } },
                ],
              },
            },
            // config may only import modules for routes
            {
              from: { file: { categories: 'config' } },
              disallow: { to: { element: { type: '*' } } },
              message: 'Config modules can only import routes, utils and auth services',
            },
            {
              from: { file: { categories: 'config' } },
              allow: {
                to: [
                  { file: { categories: 'routes' } },
                  { element: { type: 'service', captured: { context: 'auth' } } },
                  { element: { type: 'util', captured: { context: 'shared' } } },
                ],
              },
            },
            // modules for routes may import feature components
            {
              from: { file: { categories: 'routes' } },
              allow: { to: { element: { type: 'features' } } },
            },
            // modules for routes may not import ui components
            {
              from: { file: { categories: 'routes' } },
              disallow: { to: { element: { type: 'ui' } } },
              message: 'Modules for routes cannot import ui components',
            },
            // mocks are exempt from all rules, except the mock rule further below
            {
              from: { element: { type: 'mock' } },
              allow: { to: { element: { type: '*' } } },
            },
            // disallow importing from higher levels
            {
              from: { element: { type: 'ui' } },
              disallow: { to: { element: { type: 'features' } } },
              message: 'UI components should not import feature components',
            },
            {
              from: { element: { type: 'ui' } },
              disallow: { to: { element: { type: 'service' } } },
              message: 'UI components should not import services',
            },
            {
              from: { element: { type: ['service', 'pipe', 'model', 'util'] } },
              disallow: { to: { element: { type: ['features', 'ui'] } } },
              message: 'Components should not be imported from other kinds of modules',
            },
            {
              from: { element: { type: 'pipe' } },
              disallow: { to: { element: { type: 'service' } } },
              message: 'Services should not be imported from pipes',
            },
            {
              from: { element: { type: 'model' } },
              disallow: { to: { element: { type: ['service', 'pipe'] } } },
              message: 'Services and pipes should not be imported from models',
            },
            {
              from: { element: { type: 'util' } },
              disallow: { to: { element: { type: ['service', 'pipe'] } } },
              message: 'Services and pipes should not be imported from utilities',
            },
            // Auth service may be imported in other contexts
            {
              from: [
                { element: { type: ['features', 'service'] } },
                { file: { categories: 'routes' } },
              ],
              allow: {
                to: { element: { type: 'service', captured: { context: 'auth' } } },
              },
            },
            // Auth models may be imported in other contexts
            {
              from: { element: { type: ['features', 'service', 'model', 'mock'] } },
              allow: {
                to: { element: { type: 'model', captured: { context: 'auth' } } },
              },
            },

            // Mock module may only import models
            {
              from: { element: { type: 'mock' } },
              disallow: { to: { element: { type: '!model' } } },
              message: 'Mock modules can only import models {{to.captured.context}}',
            },
            // Tests are currently exempt from all rules. Spec files are a file
            // category rather than an element, so they also match the element rules
            // for the folder they live in; this exemption must stay last to win.
            // The target list covers both layers because some import targets (config,
            // routes, the main app component) are categorised files without an element.
            {
              from: { file: { categories: 'spec' } },
              allow: {
                to: [{ element: { type: '*' } }, { file: { categories: '*' } }],
              },
            },
          ],
        },
      ],
    },
    settings: {
      'boundaries/legacy-templates': false,
      'import/resolver': {
        typescript: {
          alwaysTryTypes: true,
        },
      },
      // Element patterns match folders, so single files are classified here instead,
      // by category. A file can carry a category and still belong to an element:
      // `src/app/metadata/ui/x.spec.ts` is category `spec` inside the `ui` element.
      'boundaries/files': [
        { category: 'main', pattern: 'src/main.ts' },
        { category: 'config', pattern: 'src/app/**/*.config.ts' },
        { category: 'main-app', pattern: 'src/app/app.ts' },
        { category: 'routes', pattern: 'src/app/**/*-routes.ts' },
        { category: 'spec', pattern: 'src/app/**/*.spec.ts|tests/**/*.ts' },
        {
          category: 'tooling',
          pattern: ['setup-test.ts', 'playwright.config.ts', 'vitest.config.ts'],
        },
      ],
      'boundaries/elements': [
        // The first matching pattern will be used as the element type.
        // The element types correspond to the layers of the architecture matrix.
        // The name of the vertical slice is captured as the context value.
        {
          type: 'features',
          pattern: 'src/app/*/features',
          capture: ['context'],
        },
        {
          type: 'ui',
          pattern: 'src/app/*/ui',
          capture: ['context'],
        },
        {
          type: 'service',
          pattern: 'src/app/*/services',
          capture: ['context'],
        },
        {
          type: 'pipe',
          pattern: 'src/app/*/pipes',
          capture: ['context'],
        },
        {
          type: 'model',
          pattern: 'src/app/*/models',
          capture: ['context'],
        },
        {
          type: 'util',
          pattern: 'src/app/*/utils',
          capture: ['context'],
        },
        {
          type: 'mock',
          pattern: 'src/mocks',
        },
      ],
    },
  },
  // Configuration for HTML template files
  {
    files: ['src/app/**/*.html'],
    extends: [
      angularEslint.configs.templateRecommended,
      angularEslint.configs.templateAccessibility,
    ],
    plugins: {
      local: {
        rules: {
          'umami-event-max-length': umamiEventMaxLength,
        },
      },
    },
    rules: {
      '@angular-eslint/template/no-positive-tabindex': 'error',
      'local/umami-event-max-length': 'error',
    },
  },
  // Configuration for Markdown files
  {
    files: ['**/*.md'],
    plugins: {
      markdown,
    },
    language: 'markdown/commonmark',
    rules: {
      'markdown/fenced-code-language': 'error',
      'markdown/heading-increment': 'error',
      'markdown/no-duplicate-headings': 'error',
      'markdown/no-empty-links': 'error',
      'markdown/no-html': 'error',
      'markdown/no-invalid-label-refs': 'error',
      'markdown/no-missing-label-refs': 'error',
    },
  },
  // Disable ESLint rules that conflict with Prettier (must come last).
  // Prettier itself runs as a standalone tool via `pnpm format`.
  eslintConfigPrettier,
);
