allowBuilds:
  '@compodoc/compodoc': true
  '@parcel/watcher': true
  '@tailwindcss/oxide': true
  esbuild: true
  lmdb: true
  msgpackr-extract: true
  msw: true
  unrs-resolver: true
minimumReleaseAgeExclude:
  - ngx-mat-input-tel@22.0.1
