[build-system]
requires = [
    "setuptools>=82",
]
build-backend = "setuptools.build_meta"

[project]
readme = "README.md"
authors = [
    { name = "German Human Genome Phenome Archive (GHGA)", email = "contact@ghga.de" },
]
requires-python = ">=3.13"
classifiers = [
    "Development Status :: 5 - Production/Stable",
    "Operating System :: POSIX :: Linux",
    "Programming Language :: Python :: 3",
    "Programming Language :: Python :: 3.13",
    "License :: OSI Approved :: Apache Software License",
    "Topic :: Internet :: WWW/HTTP :: HTTP Servers",
    "Topic :: Software Development :: Libraries",
    "Intended Audience :: Developers",
]
name = "auth-service"
version = "10.0.1"
description = "Authentication adapter and services used for the GHGA data portal"
dependencies = [
    "ghga-event-schemas~=13.0.0",
    "ghga-service-commons[api,auth]>=7,<8",
    "hexkit[mongodb,akafka,opentelemetry-akafka,opentelemetry-mongodb,opentelemetry-fastapi]>=8.4, <9",
    "pynacl>=1.6,<2",
    "pyotp>=2.9,<3",
    "httpx>=0.28,<0.29",
    "phonenumbers>=9,<10",
]

[project.license]
text = "Apache 2.0"

[project.urls]
Repository = "https://github.com/ghga-de/auth-service"

[project.scripts]
auth-service = "auth_service.__main__:run"

[tool.setuptools.packages.find]
where = [
    "src",
]

[tool.pytest.ini_options]
minversion = "9.0"
asyncio_mode = "strict"
asyncio_default_fixture_loop_scope = "function"
testpaths = [
    "tests/unit",
    "tests/integration",
]

[tool.coverage.paths]
source = [
    "src",
    "/workspace/src",
    "**/lib/python*/site-packages",
]

[tool.uv.sources]
ghga-event-schemas = { workspace = true }
ghga-service-commons = { workspace = true }
hexkit = { workspace = true }
