image:
  repository: "ghga/file-ingest-service"

configPrefix: fis

# Service parameters

# Service base path
apiBasePath: /fis/
# Name of the database
mongodb:
  dbName: file-ingest

# This parameter is used as Kafka's group id
serviceName: fis-rest

config:
  host: 0.0.0.0
  mongo_dsn: null
  db_version_collection: "fisDbVersions"
  migration_wait_sec: 10
  enable_opentelemetry: false
  ekss_api_url: http://encryption-key-store:8080

cmd: fis run-rest

_topics:
  fileUploadValidationSuccess:
    # as producer
    topic:
      name: file_interrogations_topic
      value: interrogations
    types:
      - name: interrogation_success_type
        value: file_interrogation_success
      - name: interrogation_failure_type
        value: file_interrogation_failed
    kafkaUser:
      operations:
        - Write
  fileUpload:
    # as consumer
    topic:
      name: file_upload_topic
      value: file-uploads
    kafkaUser:
      operations:
        - Read
